// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdlkbfhnzbiqjkqmweim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbGtiZmhuemJpcWprcW13ZWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Nzk1ODgsImV4cCI6MjA4OTI1NTU4OH0.TfxYXs5Xb9CDTBVWwxUr65-s06wKzglUYI-uvYDlhyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});